
export const LOGIN = 'AUTH_0/LOGIN';
export const HANDLE_AUTHENTICATION = 'AUTH_0/HANDLE_AUTHENTICATION';
export const CHECK_SESSION = 'AUTH_0/CHECK_SESSION';
export const LOGOUT = 'AUTH_0/LOGOUT';

export const SET_INTENTED_ROUTE = 'AUTH_0/SET_INTENTED_ROUTE';
export const SUCCESS = 'AUTH_0/AUTH_SUCCESS';
export const ERROR = 'AUTH_0/AUTH_ERROR';